# Generated by Django 4.2.30 on 2026-09-02 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150, unique=True)),
                ('contact_person', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(choices=[('MEAT', 'Meat & Poultry'), ('PRODUCE', 'Produce'), ('DAIRY', 'Dairy'), ('DRY', 'Dry Goods'), ('FROZEN', 'Frozen'), ('CHILLED', 'Chilled'), ('BEVERAGE', 'Beverages'), ('PACKAGING', 'Packaging'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('lead_time_days', models.PositiveIntegerField(default=3, help_text='Average delivery lead time in days')),
                ('rating', models.DecimalField(decimal_places=2, default=0, help_text='0.00 - 5.00', max_digits=3)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['company_name'],
            },
        ),
    ]
