# Generated by Django 4.2.30 on 2026-09-02 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '__first__'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='supplier_fk',
            field=models.ForeignKey(blank=True, help_text='Linked supplier (preferred)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredients', to='suppliers.supplier'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='supplier',
            field=models.CharField(blank=True, help_text='Legacy free-text (migrated to supplier_fk)', max_length=150),
        ),
    ]
