# Generated by Django 5.2.17 on 2026-09-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_ingredient_supplier_fk_alter_ingredient_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='PHP per unit - for inventory valuation', max_digits=12),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='notes',
            field=models.CharField(blank=True, help_text='Additional details', max_length=255),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='reason',
            field=models.CharField(choices=[('NORMAL_USAGE', 'Normal Usage'), ('SPOILAGE_WASTE', 'Spoilage/Waste'), ('DAMAGED', 'Damaged'), ('OTHER', 'Other')], default='NORMAL_USAGE', max_length=20),
        ),
    ]
