# Generated by Django 5.2.17 on 2026-09-05 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forecasting', '0002_aiprocurementalert_accuracy_note_and_more'),
        ('inventory', '0003_ingredient_unit_cost_stocktransaction_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIVarianceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_stockout_date', models.DateField()),
                ('actual_zero_date', models.DateField()),
                ('variance_days', models.IntegerField(help_text='actual - predicted (positive = AI early, negative = AI late)')),
                ('predicted_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variance_logs', to='forecasting.aiprocurementalert')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variance_logs', to='inventory.ingredient')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ingredient', 'created_at'], name='reports_aiv_ingredi_2197c1_idx')],
            },
        ),
    ]
