# Generated by Django 4.2.30 on 2026-09-02 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '__first__'),
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementrequest',
            name='auto_generated',
            field=models.BooleanField(default=False, help_text='Created by AI forecasting'),
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='delivered_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual delivered qty', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='expected_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Assigned supplier for fulfillment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_requests', to='suppliers.supplier'),
        ),
    ]
