# Generated by Django 5.2.17 on 2026-09-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_procurementrequest_auto_generated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementrequest',
            name='actual_delivery_date',
            field=models.DateField(blank=True, help_text='Actual delivery - for reliability metrics', null=True),
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='expected_delivery_date',
            field=models.DateField(blank=True, help_text='Expected supplier delivery', null=True),
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='PHP per unit at procurement time', max_digits=12),
        ),
        migrations.AlterField(
            model_name='procurementrequest',
            name='expected_date',
            field=models.DateField(blank=True, help_text='Legacy alias - use expected_delivery_date', null=True),
        ),
    ]
