# Generated by Django 4.2.30 on 2026-09-02 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0002_ingredient_supplier_fk_alter_ingredient_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProcurementAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('predicted_stockout_date', models.DateField(blank=True, null=True)),
                ('daily_usage', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('days_until_stockout', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('risk', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='LOW', max_length=10)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CONVERTED', 'Converted to Request')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_alerts', to='inventory.ingredient')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'risk'], name='forecasting_status_dc34d8_idx')],
            },
        ),
    ]
