# Generated by Django 5.2.17 on 2026-09-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiprocurementalert',
            name='accuracy_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='aiprocurementalert',
            name='actual_zero_date',
            field=models.DateField(blank=True, help_text='Date ingredient actually hit zero', null=True),
        ),
        migrations.AddField(
            model_name='aiprocurementalert',
            name='variance_days',
            field=models.IntegerField(blank=True, help_text='actual - predicted days (positive = late, negative = early)', null=True),
        ),
    ]
